// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Void.API.Data;

#nullable disable

namespace Void.API.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260610021439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Void.API.Models.AlertaCriticoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SESSAO");

                    b.Property<decimal?>("NivelAtingido")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("NIVEL_ATINGIDO");

                    b.Property<int>("PacienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACIENTE_ID");

                    b.Property<DateTime>("TimestampAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("TIMESTAMP_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "DataSessao");

                    b.ToTable("ALERTA_CRITICO");
                });

            modelBuilder.Entity("Void.API.Models.LeituraFadigaEntity", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACIENTE_ID");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SESSAO");

                    b.Property<int>("SegundoLeitura")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SEGUNDO_LEITURA");

                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<decimal>("PercentualDesgaste")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PERCENTUAL_DESGASTE");

                    b.HasKey("PacienteId", "DataSessao", "SegundoLeitura");

                    b.HasIndex("IdSensor");

                    b.ToTable("LEITURA_FADIGA");
                });

            modelBuilder.Entity("Void.API.Models.LogAuditoriaSessaoEntity", b =>
                {
                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ACAO");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<DateTime?>("DataSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SESSAO");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACIENTE_ID");

                    b.Property<string>("StatusAntigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_ANTIGO");

                    b.ToTable("LOG_AUDITORIA_SESSAO");
                });

            modelBuilder.Entity("Void.API.Models.ProtocoloEspacialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROTOCOLO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LimiteFadigaMaxima")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("LIMITE_FADIGA_MAXIMA");

                    b.Property<string>("NomeProtocolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PROTOCOLO");

                    b.HasKey("Id");

                    b.ToTable("PROTOCOLO_ESPACIAL");
                });

            modelBuilder.Entity("Void.API.Models.SensorWearableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("MAC_ADDRESS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("SENSOR_WEARABLE");
                });

            modelBuilder.Entity("Void.API.Models.SessaoReabilitacaoEntity", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACIENTE_ID");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SESSAO");

                    b.Property<int?>("AlertaFadigaCritica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALERTA_FADIGA_CRITICA");

                    b.Property<decimal?>("DesgasteAcumulado")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DESGASTE_ACUMULADO");

                    b.Property<int>("IdFisio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FISIO");

                    b.Property<int>("IdProtocolo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROTOCOLO");

                    b.Property<string>("StatusSessao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_SESSAO");

                    b.HasKey("PacienteId", "DataSessao");

                    b.HasIndex("IdFisio");

                    b.HasIndex("IdProtocolo");

                    b.ToTable("TB_VOID_SESSAO_REABILITACAO");
                });

            modelBuilder.Entity("Void.API.Models.TelemetriaRawJsonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DadosJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DADOS_JSON");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SESSAO");

                    b.Property<int>("PacienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PACIENTE_ID");

                    b.HasKey("Id");

                    b.ToTable("TELEMETRIA_RAW_JSON");
                });

            modelBuilder.Entity("Void.API.Models.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("Id");

                    b.ToTable("TB_VOID_USUARIO", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Void.API.Models.FisioterapeutaEntity", b =>
                {
                    b.HasBaseType("Void.API.Models.UsuarioEntity");

                    b.Property<string>("RegistroProfissional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("REGISTRO_PROFISSIONAL");

                    b.ToTable("TB_VOID_FISIOTERAPEUTA", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("ID_USUARIO");
                        });
                });

            modelBuilder.Entity("Void.API.Models.PacienteEntity", b =>
                {
                    b.HasBaseType("Void.API.Models.UsuarioEntity");

                    b.Property<decimal>("LimiteEsforcoCritico")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("LIMITE_ESFORCO_CRITICO");

                    b.ToTable("TB_VOID_PACIENTE", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("ID_USUARIO");
                        });
                });

            modelBuilder.Entity("Void.API.Models.AlertaCriticoEntity", b =>
                {
                    b.HasOne("Void.API.Models.SessaoReabilitacaoEntity", null)
                        .WithMany()
                        .HasForeignKey("PacienteId", "DataSessao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Void.API.Models.LeituraFadigaEntity", b =>
                {
                    b.HasOne("Void.API.Models.SensorWearableEntity", "Sensor")
                        .WithMany()
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Void.API.Models.SessaoReabilitacaoEntity", "Sessao")
                        .WithMany("Leituras")
                        .HasForeignKey("PacienteId", "DataSessao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Void.API.Models.SessaoReabilitacaoEntity", b =>
                {
                    b.HasOne("Void.API.Models.FisioterapeutaEntity", "Fisioterapeuta")
                        .WithMany()
                        .HasForeignKey("IdFisio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Void.API.Models.ProtocoloEspacialEntity", "Protocolo")
                        .WithMany()
                        .HasForeignKey("IdProtocolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Void.API.Models.PacienteEntity", "Paciente")
                        .WithMany("Sessoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");

                    b.Navigation("Protocolo");
                });

            modelBuilder.Entity("Void.API.Models.FisioterapeutaEntity", b =>
                {
                    b.HasOne("Void.API.Models.UsuarioEntity", null)
                        .WithOne()
                        .HasForeignKey("Void.API.Models.FisioterapeutaEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Void.API.Models.PacienteEntity", b =>
                {
                    b.HasOne("Void.API.Models.UsuarioEntity", null)
                        .WithOne()
                        .HasForeignKey("Void.API.Models.PacienteEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Void.API.Models.SessaoReabilitacaoEntity", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Void.API.Models.PacienteEntity", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
